---
          - name : get firefox 
            get_url:
                    url: https://ftp.mozilla.org/pub/firefox/releases/{{ item }}.0/linux-x86_64/en-US/firefox-{{ item }}.0.tar.bz2 
                    dest: "{{ HOME_DIR }}/Downloads" 
            with_items: 
              - "{{ FIREFOX_VERSION }}"


          - name: create extract location
            file: 
               path: "{{ HOME_DIR }}/Downloads/firefox-{{ item }}"
               state: directory 
            with_items:
              - "{{ FIREFOX_VERSION }}"

          - name: extract firefox 
            unarchive:
                    src: "{{ HOME_DIR }}/Downloads/firefox-{{ item }}.0.tar.bz2"
                    dest: "{{ HOME_DIR }}/Downloads/firefox-{{ item }}"
                    remote_src: true
            with_items:
              - "{{ FIREFOX_VERSION }}"


          - name: remove any pre-installed firefox browsers
            package:
                    name: firefox
                    state: absent
          - name: find the firefox defaults directory
            find:
               paths: "{{ HOME_DIR }}/.mozilla/firefox"
               patterns: "prefs.js"
               file_type: file
               recurse: yes
            register: FIREFOX_DEFAULTS_PATH       

          - name: add settings to prefs.js that stops automatic updates -firefox
            lineinfile: 
                     name: "{{ item.path }}"
                     line: 'user_pref("app.update.auto", false);'
            with_items: "{{ FIREFOX_DEFAULTS_PATH.files }}"

          - name: add settings to prefs.js that disable updates - firefox
            lineinfile: 
                     name: "{{ item.path }}"
                     line: 'user_pref("app.update.enabled", false);'
            with_items: "{{ FIREFOX_DEFAULTS_PATH.files }}"

          - name: add alias to firefox e.g. firefox54 will launch {{HOME_DIR}}/Downloads/firefox-54/firefox/./firefox
            lineinfile:
                    name: "{{ HOME_DIR}}/.bashrc"
                    line: 'alias firefox{{ item }}="{{ HOME_DIR }}/Downloads/firefox-{{ item }}/firefox/./firefox"'
            with_items: "{{ FIREFOX_VERSION }}"

