---
- hosts: vmrc-linux
  pre_tasks: 
      - name: install python2
        package:
                name: python
                state: latest

      - name: install python2-dnf
        package:
                name: python2-dnf
                state: latest
        when: ansible_distribution == "Fedora"

      - name: install libselinux-python
        package: 
                name: libselinux-python 
                state: latest

  tasks: 
      - name: copy google-chrome.repo
        copy: 
           src: google-chrome.repo
           dest: /etc/yum.repos.d/
           owner: root
           group: root
           mode: 644

      - name: install  google chrome
        package:
          name: google-chrome-stable
          state: present

