---
- hosts: vmrc-linux
  vars_prompt:
          - name: "VMRC_LOCATION"
            prompt: "Enter url of VMRC .bundle file(wget compatible):"
            default: file.rdu.redhat.com/~mpusater/VMware-Remote-Console-9.0.0-4288332.x86_64.bundle
  tasks:
          - name: get vmrc .bundle from fileserver
            get_url:
                    url: http://{{ VMRC_LOCATION }}
                    dest: /root/Downloads/vmrc.bundle
                    mode: 0776
          - name: install pexpect module from pip
            pip: 
               name: pexpect

          - name: launch vmrc script
            expect: 
                 command: /root/Downloads/./vmrc.bundle --console
                 responses: 
                        '.*?': "\n"
