---
- name: Setup VMRC Test compatible Envrionment
  hosts: all
  roles:
    - { role: install_firefox_on_linux, tags: firefox }
    - { role: install_chrome_on_fedora, when: ansible_distribution == "Fedora", tags: chrome_fedora}
    - { role: install_chrome_on_rhel, when: ansible_distribution == "RedHat", tags: chrome_rhel }
    - { role: install_vmrc_on_linux, tags: vmrc }

