---
  - name: copy google-chrome.repo
    copy: 
      src: files/google-chrome.repo
      dest: /etc/yum.repos.d/
      owner: root
      group: root
      mode: 644
      remote_src: no

  - name: install  google chrome
    package:
      name: google-chrome-stable
      state: present


