---
          - name: get vmrc .bundle from fileserver
            get_url:
                    url: http://{{ VMRC_LOCATION }}
                    dest: "{{ HOME_DIR }}/Downloads/vmrc.bundle"
                    mode: 0776
                    group: cfme-qe

          - name: install vmrc interactively
            command: /bin/sh -c "yes n| {{ HOME_DIR }}/Downloads/./vmrc.bundle --console --eulas-agreed"
